# Generated by Django 2.2.4 on 2019-08-20 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ap_hi', models.IntegerField()),
                ('ap_lo', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('gluc', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('alco', models.IntegerField()),
                ('active', models.IntegerField()),
                ('cardio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nacimiento', models.DateTimeField()),
                ('genero', models.IntegerField(choices=[(1, 'Mujer'), (2, 'Hombre')], default='Hombre')),
                ('altura_en_cm', models.IntegerField()),
                ('peso_en_kg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('presión_sanguínea_sistólica', models.IntegerField()),
                ('colesterol', models.IntegerField(choices=[(1, 'Normal'), (2, 'Encima de Normal'), (3, 'Muy por Encima de Normal')], default='Normal')),
                ('glucosa', models.IntegerField(choices=[(1, 'Normal'), (2, 'Encima de Normal'), (3, 'Muy por Encima de Normal')], default='Normal')),
                ('fuma', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default='No')),
                ('consume_alcohol', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default='No')),
                ('actividad_física', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default='No')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
