# Generated by Django 2.2.4 on 2019-08-29 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predecir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cedula',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='sino',
            field=models.IntegerField(default=0),
        ),
    ]
