# Generated by Django 2.2.4 on 2019-08-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predecir', '0003_auto_20190828_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='altura_en_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='peso_en_kg',
            field=models.DecimalField(decimal_places=1, default=0.001, max_digits=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='presión_sanguínea_sistólica',
            field=models.IntegerField(default=0),
        ),
    ]
