# Generated by Django 2.2.4 on 2019-08-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predecir', '0004_auto_20190828_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='peso_en_kg',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
