# Generated by Django 2.2.4 on 2019-08-29 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predecir', '0005_auto_20190828_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
