# Generated by Django 2.2.4 on 2019-08-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predecir', '0006_auto_20190829_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='presión_sanguínea_diastolica',
            field=models.IntegerField(default=0),
        ),
    ]
