# Generated by Django 2.2.4 on 2019-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predecir', '0007_persona_presión_sanguínea_diastolica'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultaForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
            ],
        ),
    ]
